### ISSUE TITLE
Implement Navigator

### ISSUE THREAD

**Issue by samuelblattner** [openscript/ffhs-esa#22]
Implement the Navigator class to gather Location information and notify all its observers upon Location, Speed and Road changes. Keep track of an amount of MAX_LOCATION_HISTORY_ITEMS past Locations. See https://developers.google.com/maps/documentation/roads/advanced for Roads API reference.

Notify observers on Service Status changes using the [ifNavigationObserver](https://github.com/openscript/ffhs-esa/blob/master/app/src/main/java/ch/ffhs/students/speedbump/navigator/ifNavigationObserver.java) interface and the [NavigatorStatus](https://github.com/openscript/ffhs-esa/blob/master/app/src/main/java/ch/ffhs/students/speedbump/navigator/enums/NavigatorStatus.java) enum.

**Comment by openscript** [comment]
Speed limit from openstreet map implemented. It's a bit shaky right now.
